"""update2

Revision ID: 58dd2d416dc7
Revises: a851384bb9f1
Create Date: 2024-12-09 19:33:58.876902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58dd2d416dc7'
down_revision = 'a851384bb9f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)

    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index('ix_instrument_category_price', ['category_id', 'price'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_name'), ['name'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_name'))
        batch_op.drop_index(batch_op.f('ix_instruments_category_id'))
        batch_op.drop_index('ix_instrument_category_price')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))

    # ### end Alembic commands ###
